I was unable to run the Zulip server for the entire day, which was only fixed by moving to another computer entirely.
Other than that, I had to make a couple of global variables in links.py to fix some errors.
